# Generated by Django 4.2.28 on 2026-02-07 06:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("total_requests", models.IntegerField(default=0)),
                ("auto_approved", models.IntegerField(default=0)),
                ("auto_blocked", models.IntegerField(default=0)),
                ("sent_to_review", models.IntegerField(default=0)),
                ("accuracy_percent", models.FloatField(default=0.0)),
                ("false_positive_rate", models.FloatField(default=0.0)),
                ("false_negative_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Daily metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="FraudReadinessSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("simulated_pattern", models.CharField(max_length=64)),
                ("simulated_risk_score", models.IntegerField()),
                (
                    "readiness_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                ("payment_method_id", models.CharField(max_length=255)),
                ("payment_method_age_days", models.IntegerField()),
                ("country", models.CharField(max_length=255)),
                ("ip_address", models.GenericIPAddressField()),
                ("vpn_detected", models.BooleanField(default=False)),
                ("total_trades", models.IntegerField(default=0)),
                (
                    "total_trade_volume",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("risk_score", models.IntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("review", "Review"),
                            ("block", "Block"),
                        ],
                        max_length=10,
                    ),
                ),
                ("confidence_score", models.IntegerField()),
                (
                    "regret_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        max_length=10,
                    ),
                ),
                ("triggered_signals", models.JSONField(default=list)),
                ("reasons", models.JSONField(default=list)),
                ("counterfactuals", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payout_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_decision",
                        to="risk_engine.payoutrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HumanReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reviewer_id", models.CharField(max_length=255)),
                (
                    "final_decision",
                    models.CharField(
                        choices=[("approve", "Approve"), ("block", "Block")],
                        max_length=10,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "risk_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="human_reviews",
                        to="risk_engine.riskdecision",
                    ),
                ),
            ],
            options={
                "ordering": ["-reviewed_at"],
            },
        ),
    ]
