# Generated by Django 4.2.28 on 2026-02-07 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_engine", "0001_core_domain_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalibrationStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("reviewed_count", models.IntegerField(default=0)),
                ("correct_count", models.IntegerField(default=0)),
                ("incorrect_count", models.IntegerField(default=0)),
                ("accuracy_percent", models.FloatField(default=0.0)),
                ("avg_confidence_correct", models.FloatField(default=0.0)),
                ("avg_confidence_incorrect", models.FloatField(default=0.0)),
                ("overconfidence_rate", models.FloatField(default=0.0)),
                ("underconfidence_rate", models.FloatField(default=0.0)),
            ],
            options={
                "verbose_name_plural": "Calibration stats",
                "ordering": ["-date"],
            },
        ),
    ]
