# Generated by Django 4.2.28 on 2026-02-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_engine", "0002_add_calibration_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngineConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("value", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name_plural": "Engine config",
            },
        ),
        migrations.AddField(
            model_name="humanreview",
            name="approved_for_learning",
            field=models.BooleanField(
                default=False,
                help_text="Admin approved this override so signal weights can be tuned from it.",
            ),
        ),
        migrations.AddField(
            model_name="humanreview",
            name="note",
            field=models.TextField(
                blank=True,
                help_text="Optional note from the reviewer when overturning.",
            ),
        ),
        migrations.AddField(
            model_name="humanreview",
            name="system_explanation",
            field=models.TextField(
                blank=True,
                help_text="LLM-generated: why the system made its decision (filled on first admin view).",
            ),
        ),
    ]
