# Generated by Django 4.2.28 on 2026-02-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_engine", "0003_add_review_note_and_engine_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "System scores",
            },
        ),
        migrations.AddField(
            model_name="riskdecision",
            name="review_explanation",
            field=models.TextField(
                blank=True,
                help_text="LLM-generated: why this was sent for review (filled on first request when decision=review).",
            ),
        ),
    ]
