# Generated by Django 4.2.28 on 2026-02-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("risk_engine", "0004_add_review_explanation_and_system_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("reason", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergingPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("signal_combo", models.CharField(max_length=256)),
                ("case_count", models.IntegerField(default=0)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="card_decline_count_24h",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="device_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="payoutrequest",
            name="failed_login_count_24h",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
