"""
Deterministic fraud detection and scoring engine.

Detectors and scoring are pure and deterministic. Reasons and counterfactuals
are generated by LLM when OPENAI_API_KEY is set; otherwise fallback to deterministic text.
"""

from .decisioning import get_decision, get_regret_level, get_confidence_score
from .detectors import run_all_detectors
from .explanations import get_reasons, get_counterfactuals
from .scoring import compute_risk_score
from .types import EngineInput, EngineResult


def _engine_input_to_dict(input: EngineInput) -> dict:
    """Serialize EngineInput to a JSON-serializable dict for the LLM payload."""
    return {
        "user_id": input.user_id,
        "amount": float(input.amount),
        "currency": input.currency,
        "payment_method_id": input.payment_method_id,
        "payment_method_age_days": input.payment_method_age_days,
        "country": input.country,
        "ip_address": input.ip_address,
        "vpn_detected": input.vpn_detected,
        "total_trades": input.total_trades,
        "total_trade_volume": float(input.total_trade_volume),
        "withdrawals_last_1h": input.withdrawals_last_1h,
        "withdrawals_last_24h": input.withdrawals_last_24h,
        "deposits_last_1h": input.deposits_last_1h,
        "expected_country": input.expected_country,
    }


def run_engine(input: EngineInput) -> EngineResult:
    """
    Compute triggered signals, risk score, decision (deterministic), then generate
    reasons and counterfactuals via LLM or fallback.
    """
    triggered_signals = run_all_detectors(input)
    risk_score = compute_risk_score(triggered_signals)
    decision = get_decision(risk_score)
    regret_level = get_regret_level(input.amount)
    confidence_score = get_confidence_score(input, risk_score, triggered_signals)

    from risk_engine.llm.client import generate_explanations
    payload = {
        "engine_input": _engine_input_to_dict(input),
        "triggered_signals": triggered_signals,
        "decision": decision,
        "risk_score": risk_score,
        "confidence_score": confidence_score,
        "regret_level": regret_level,
    }
    explanations = generate_explanations(payload)
    reasons = explanations.get("reasons") or []
    counterfactuals = explanations.get("counterfactuals") or []
    if not reasons and triggered_signals:
        reasons = get_reasons(input, triggered_signals)
    if not counterfactuals and triggered_signals:
        counterfactuals = get_counterfactuals(input, triggered_signals)

    return EngineResult(
        triggered_signals=triggered_signals,
        risk_score=risk_score,
        confidence_score=confidence_score,
        regret_level=regret_level,
        decision=decision,
        reasons=reasons,
        counterfactuals=counterfactuals,
    )

__all__ = [
    "EngineInput",
    "EngineResult",
    "run_engine",
    "run_all_detectors",
    "compute_risk_score",
    "get_decision",
    "get_regret_level",
    "get_confidence_score",
    "get_reasons",
    "get_counterfactuals",
]
